//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hotel_Management
{
    using System;
    using System.Collections.Generic;
    
    public partial class Booking
    {
        public int Booking_Id { get; set; }
        public Nullable<int> B_User_Id { get; set; }
        public Nullable<int> B_Room_Id { get; set; }
        public string Status { get; set; }
    
        public virtual Userdata Userdata { get; set; }
        public virtual RoomData RoomData { get; set; }
    }
}
