//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hotel_Management
{
    using System;
    using System.Collections.Generic;
    using System.Web;

    public partial class Hotel_Data
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Hotel_Data()
        {
            this.RoomDatas = new HashSet<RoomData>();
        }
    
        public int Hotel_Id { get; set; }
        public string Hotel_name { get; set; }
        public string City { get; set; }
        public string Rating { get; set; }
        public string img1 { get; set; }
        public string img2 { get; set; }

        public HttpPostedFileBase ImageFile1 { get; set; }

        public HttpPostedFileBase ImageFile2 { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RoomData> RoomDatas { get; set; }
    }
}
