//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hotel_Management
{
    using System;
    using System.Collections.Generic;
    
    public partial class RoomData
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public RoomData()
        {
            this.Bookings = new HashSet<Booking>();
        }
    
        public int Room_Id { get; set; }
        public Nullable<int> R_Hotel_Id { get; set; }
        public string Type { get; set; }
        public Nullable<int> Price { get; set; }
        public Nullable<int> Capacity { get; set; }
        public Nullable<int> No_rooms { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Booking> Bookings { get; set; }
        public virtual Hotel_Data Hotel_Data { get; set; }
        public virtual Userdata Userdata { get; set; }
    }
}
